CrowdStrike/ember-headless-table

- docs-app/package.json
- docs/demos/kitchen-sink/demo/demo-a.md
- docs/demos/kitchen-sink/index.md
- docs/demos/lots-of-data/demo/demo-a.md
- docs/demos/lots-of-data/index.md
- pnpm-lock.yaml
Only two demos for now
- dbmon
- "kitchen sink" -- though this is a copy of the main demo for now, because this is waiting on [this PR](https://github.com/CrowdStrike/ember-headless-table/pull/4) before adding more stuff
If anyone has other ideas for "how to do X", those would be a good candidate for these types of docs.
Later, we'll probably want a whole separate page / nav for _most_ of these kinds of demos, as we may have a lot.
Funnest demo: https://8dbbebed.ember-headless-table.pages.dev/docs/demos/lots-of-data
After working with these demos a bit, I'm going to be spending some of my time working with Docfy to make the authoring experience a bit better:
- actual js/ts/hbs/gjs/gts files
- inline gjs demos (no demos folder)
- probably other stuff
> Cookbook docs

- docs/demos/custom-cells/demo/demo-a.md
- docs/demos/custom-cells/index.md
customizing cell is not only common, but there should probably be demos for each feature ember-headless-table supports (tbd/coming soon).
> chore(docs): add custom cell demo

- ember-headless-table/src/-private/row.ts
- ember-headless-table/src/-private/table.ts
[This PR](https://github.com/CrowdStrike/ember-headless-table/pull/12) got a little big, so I've extracted the deprecated API cleanup to this PR.
All code removed in this PR is from an earlier time (still pre-release), and can be implemented via plugins, or via component composition by the consumer.
Behavior to implement and document after this PR:
_(will link back here as the features are implemented in other PRs)_
> chore(cleanup): remove remaining deprecated APIs

- docs/plugins/column-resizing/demo/demo-a.md
- ember-headless-table/src/plugins/column-reordering/plugin.ts
- ember-headless-table/src/plugins/column-resizing/plugin.ts
- test-app/tests/plugins/column-resizing/rendering-test.gts
- test-app/tests/plugins/sticky-columns/rendering-test.gts
Requires https://github.com/CrowdStrike/ember-headless-table/pull/12
(will make the diff actually understandable)
Will be made simpler by: https://github.com/CrowdStrike/ember-headless-table/pull/40
(but that's not required by this work, and can lead to a nice _delete a bunch of things PR_ later
> Fix resizing column logic

- docs/demos/kitchen-sink/demo/demo-a.md
- docs/plugins/column-reordering/demo/dema-a.md
- docs/plugins/column-resizing/demo/demo-a.md
- docs/plugins/column-resizing/index.md
- docs/plugins/column-visibility/demo/demo-a.md
- docs/plugins/sticky-column/demo/demo-a.md
- docs/plugins/sticky-column/index.md
- docs/plugins/writing-your-own.md
- ember-headless-table/src/-private/interfaces/plugins.ts
- ember-headless-table/src/-private/table.ts
- ember-headless-table/src/plugins/-private/base.ts
- ember-headless-table/src/plugins/column-reordering/plugin.ts
- ember-headless-table/src/plugins/column-resizing/plugin.ts
- ember-headless-table/src/plugins/column-visibility/plugin.ts
- ember-headless-table/src/plugins/index.ts
- ember-headless-table/src/plugins/sticky-columns/plugin.ts
- pnpm-lock.yaml
- test-app/package.json
- test-app/tests/plugins/column-reordering/rendering-test.gts
- test-app/tests/plugins/column-resizing/rendering-test.gts
- test-app/tests/plugins/column-visibility/rendering-test.gts
- test-app/tests/plugins/consumption-test.ts
- test-app/tests/plugins/queries/columns-test.ts
- test-app/tests/unit/public-api-test.ts
This was a feature request / feedback from @vitch a while back when we were first open sourcing this library.
---------------
Prior to this PR, working with columns from the plugins in a hierarchical way leaked the hierarchy between the plugins, preventing consistent use of columns APIs for the consumer -- a plugin author would need to know the hierarchy, and know which plugin to access to get the correct columns.
This has now all bee abstracted away in a new set of queries helpers called `columns`.
---------------
Requires: https://github.com/CrowdStrike/ember-headless-table/pull/12
- ~~implement "optionally requires" to imply a hierarchy, as hard-requiring another plugin to be used "should be" rare~~ can be done in a later PR, when the need arises
gets the columns appropriate for the …
> Simplify working with columns

- ember-headless-table/src/plugins/column-resizing/helpers.ts
- test-app/tests/plugins/column-resizing/rendering-test.gts
as a consumer (rather than a plugin author), interacting with `meta` is cumbersome.
These additions add convenience for some of the commonly needed data provided by plugins
docs: https://2c80e8fd.ember-headless-table.pages.dev/api/functions/plugins_column_resizing_helpers.hasResizeHandle
> Add more convinience APIs

- docs-api/typedoc.config.json
Test Plan:
compare with https://ember-headless-table.pages.dev/api/modules
I don't _think_ there are any broken links anywhere.
> make docs nav less overwhelming by flattening entrypoints

- .changeset/five-impalas-flow.md
- docs/plugins/metadata/demo/demo-a.md
- docs/plugins/metadata/index.md
- ember-headless-table/package.json
- ember-headless-table/src/plugins/metadata/helpers.ts
- ember-headless-table/src/plugins/metadata/index.ts
- ember-headless-table/src/plugins/metadata/plugin.ts
- test-app/tests/plugins/metadata/rendering-test.gts
Why add this? See the changelog entry: https://github.com/CrowdStrike/ember-headless-table/pull/58/files#diff-cf61d7d4315ac16e892cfafcf5ab3fbf01c92148dc9da54de580eeb11cd8e77b
tl;dr: for consumer's organizational purposes, it'll be easier to have "arbitrary data" tied to each column and the table itself to help thread tied-to-column or tied-to-table data through multiple layers of components without having to resort to prop drilling.
_The matadata plugin could be used like a service, but scoped to "per table instance"_
We can preview the changelog entry here, once merged: https://github.com/CrowdStrike/ember-headless-table/pull/64
> Add metadata plugin for storing arbitrary information about columns and the table

- .changeset/five-impalas-flow.md
- .changeset/stale-plants-care.md
- docs/demos/external-column-ordering/demo/demo-a.md
- docs/demos/external-column-ordering/index.md
- docs/plugins/metadata/demo/demo-a.md
- docs/plugins/metadata/index.md
- ember-headless-table/package.json
- ember-headless-table/src/plugins/column-reordering/helpers.ts
- ember-headless-table/src/plugins/column-reordering/plugin.ts
- ember-headless-table/src/plugins/metadata/helpers.ts
- ember-headless-table/src/plugins/metadata/index.ts
- ember-headless-table/src/plugins/metadata/plugin.ts
- test-app/tests/plugins/column-reordering/ColumnOrder-test.ts
- test-app/tests/plugins/metadata/rendering-test.gts
Requires that https://github.com/CrowdStrike/ember-headless-table/pull/58/ be merged first.
If reviewing this before #58 is merged, here is the diff between the two branches: https://github.com/CrowdStrike/ember-headless-table/compare/metadata-plugin...demonstrate-pre-ordering-columns
> Demonstrate pre ordering columns

- docs/demos/basic-table/demo/demo-a.md
- docs/demos/basic-table/index.md
Hello 👋 
When reading the documentation it wasn't immediately clear which parts are necessary to create a minimal table. The tables under [Styles](https://ember-headless-table.pages.dev/docs/adding-style) are more or less the most basic version, but don't show how data should be passed.
To experiment with this library I've created the following basic table example. It could perhaps be useful to include something like this in the docs?
Awesome work on the library btw!
> chore(docs): add basic table example

- .changeset/slow-eagles-switch.md
- ember-headless-table/package.json
- ember-headless-table/src/-private/table.ts
- ember-headless-table/types/index.d.ts
- pnpm-lock.yaml
- test-app/tests/unit/table-test.ts
Prereq: https://github.com/CrowdStrike/ember-headless-table/pull/82, #83, #84
Resolves: https://github.com/CrowdStrike/ember-headless-table/issues/70
See changeset + test for details.
tl;dr: we can improve DX by failing as early as we can when accessing the column configs for the first time.
Without this, we'd get very hard to debug errors (especially around column re-ordering where the key of a column is very important)
> Protect against invalid column configs

- .changeset/perfect-experts-buy.md
- .github/actions/download-built-package/action.yml
- docs/plugins/sticky-column/demo/demo-a.md
- ember-headless-table/src/plugins/sticky-columns/helpers.ts
- ember-headless-table/src/plugins/sticky-columns/plugin.ts
- test-app/tests/plugins/sticky-columns/rendering-rfc-883-test.gts
re-introducing using a style string (concatenated, per plugin) until emberjs/rfcs#883 lands and is implemented.
Typically, you'd just want to let the plugin modifiers do everything, but because the sticky column / pinned columns plugin causes layout / re-paints, we want to use the style attribute to reduce the amount of content flashes for the user.
The sticky columns plugin was _initially_ implemented in this way, but was removed due to awkwardness around trying to come up with a unified API for applying styles to the style attribute across all plugins (and that's how the modifier approach came to be).
This new(yet old!) approach is specific to the sticky columns plugin, and style attribute setting is not an inherent plugin feature (as it's a one part too much wiring, as the modifiers …
> Use style tag for sticky columns instead of modifiers

- .changeset/two-meals-drive.md
- ember-headless-table/src/-private/table.ts
- ember-headless-table/src/plugins/-private/base.ts
- pnpm-lock.yaml
- test-app/ember-cli-build.js
- test-app/package.json
> Resolve memory leak found by ember-cli-memory-leak-detector

- .changeset/short-readers-joke.md
- .github/workflows/ci.yml
- docs-app/package.json
- ember-headless-table/package.json
- pnpm-lock.yaml
- test-app/config/ember-try.js
- test-app/package.json
Unblocks: https://github.com/CrowdStrike/ember-headless-table/pull/147
Adds 4.12 to the try-matrix. 
Adds v5 of ember-source to headless-table's allowed peers.
CI is green, sans: `Publish Docs to Cloudflare Pages (pull_request) Failing after 1m`
To get that working, folks'll need to use the approach for pages publishing that I'm using over at https://github.com/NullVoxPopuli/limber -- specifically: https://github.com/NullVoxPopuli/limber/blob/main/.github/workflows/deploy-preview.yml
> Be compatible with Ember v5, and add 4.12 LTS to the try matrix

- docs-app/package.json
- package.json
- pnpm-lock.yaml
- test-app/package.json
Fixes an issue where running the tests locally does not work.
see: https://github.com/embroider-build/ember-auto-import/issues/504
and: https://github.com/CrowdStrike/ember-headless-table/pull/149#discussion_r1170661625
1. we need to add ember version 5 to make the beta tests pass: 
https://github.com/CrowdStrike/ember-headless-table/pull/150
https://github.com/CrowdStrike/ember-headless-table/pull/148
2. we also need to fix `publish to cloudflare` (@ynotdraw  and I are going to take a look at this)
This is a little annoying because you have to run the tests locally.
1. checkout branch
2. `pnpm i`
3. cd to `ember-toucan-core` and then `pnpm build`
4. `pnpm i -f` (maybe...I did this tho)
5. cd to `test-app` and then `pnpm start`
6. navigate to `/tests`
> fix: Update ember auto import to 2.6.2

- .changeset/spotty-rats-love.md
- ember-headless-table/src/plugins/sticky-columns/helpers.ts
- test-app/tests/plugins/sticky-columns/rendering-rfc-883-test.gts
Some folks are having issues rendering the columns `minWidth` style because they style tag looks like:
```
style="minWidth: 40px"
```
Instead of:
```
style="min-width: 40px"
```
This hopefully fixes that?
> fix: toStyle, convert minWidth to min-width

- .changeset/soft-wolves-own.md
- .github/workflows/ci.yml
- README.md
In order to officially support Glint, support for TS < 4.8 must be dropped as Glint only supports TS 4.8+.
> Removing a TypeScript version from the support matrix is a breaking change, except when it falls out of the supported version range under the “rolling support windows” policy.
https://www.semver-ts.org/
In particular: https://www.semver-ts.org/#decouple-typescript-support-from-lts-cycles
So, this is a good time to _adopt_ a TS rolling window support policy. 
Going from a min-version to rolling support window is a breaking change.
---------------------
For the general maintenance / upkeep on this repo, the review / merge order is the following:
1. https://github.com/CrowdStrike/ember-headless-table/pull/174
1. https://github.com/CrowdStrike/ember-headless-table/pull/147
1. …
> Drop support for TS <4.8, introduce TS support rolling-window-policy

- .changeset/wet-melons-hunt.md
- docs/plugins/column-reordering/index.md
- ember-headless-table/src/plugins/column-reordering/plugin.ts
- test-app/tests/plugins/column-reordering/rendering-test.gts
enable re-ordered columns to be saved to preferences
> fix: save table column order on setAll

- .changeset/lucky-ducks-hang.md
- ember-headless-table/src/plugins/-private/base.ts
- ember-headless-table/src/plugins/column-visibility/plugin.ts
- test-app/tests/plugins/column-visibility/rendering-test.gts
When resetting column visibility preferences, each column is currently reset
separately with it's own call to the preferences service.
This update simplifies the reset by adding the `forAllColumns.delete(key: string)` method.
This clears preferences for the given key for the ColumnVisibility plugin for all columns
in a single call.
> Bulk column preferences reset

- .changeset/hot-bats-drum.md
- docs-app/package.json
- docs/plugins/column-resizing/index.md
- ember-headless-table/src/plugins/-private/base.ts
- ember-headless-table/src/plugins/column-resizing/handle.ts
- ember-headless-table/src/plugins/column-resizing/plugin.ts
- ember-headless-table/src/test-support/index.ts
- test-app/tests/plugins/column-resizing/rendering-test.gts
When columns are resized, the column widths are persisted to the preferences
> Persist column width preferences

- .changeset/fluffy-books-hope.md
- ember-headless-table/src/plugins/column-resizing/plugin.ts
- test-app/tests/plugins/column-resizing/rendering-test.gts
Saving and resetting column width preferences after resizing on a per column basis was costly and led to unexpected and sub-optimal lag in the UI when there are a lot of columns in the table.
In this PR
- When columns are resized, all visible column widths are saved in a single call to the preferences service.
- When reset, all column widths preferences are deleted (as per column visibility preferences), in a single call to the preference service.
> Column Width Preference Calls

- test-app/tests/plugins/column-resizing/column-options-test.gts
- test-app/tests/plugins/column-resizing/rendering-test.gts
await `requestAnimationFrameSettled()` before checking column width values in the DOM
some resizing tests were a bit flaky not returning the expected column widths. eg. on resetting four columns in a 1000px container the test would sometimes return the col widths as 128px (the min) rather than the expected (250px - 1/4 of the overall container width). I suspect that this is due to the test checking before the full reset and new width calculation was complete and the table fully rendered and settled.
> chore: flaky test fixes

- .changeset/fresh-oranges-scream.md
- ember-headless-table/src/plugins/column-resizing/plugin.ts
Similar to: https://github.com/CrowdStrike/ember-headless-table/blob/02b84b0069e621bfcf1b9439206c7043c9dd7dc0/ember-headless-table/src/plugins/column-resizing/resize-observer.ts#L38
The ResizeObserver checks to see if the table is destroyed, if it is, it does not create a new ResizeObserver.
This is missing in the plugin, which causes this error: `Uncaught Error: You attempted to get the value of a helper after the helper was destroyed, which is not allowed`
> fix: Resize plugin, add destroy check

- .changeset/fair-laws-serve.md
- ember-headless-table/src/plugins/column-resizing/handle.ts
- ember-headless-table/src/test-support/index.ts
- test-app/tests/plugins/column-resizing/rendering-test.gts
Turns out that this: https://github.com/CrowdStrike/ember-headless-table/pull/211#discussion_r1283447227 came back to bite us! The test was passing, but waiting in the test-helper was masking the resizing behaviour and causing unpredictable column resizing when interacting with tables.
**What was happening:**
Calling the resize function via a `requestAnimationFrame` in the `queueUpdate` pushes it into the next animation frame, however, the call to save the preferences was then happening ahead of it, so the saved values did not reflect the resizing.
We'd created a pseudo-async sequence.
**How these changes fix it:**
So, to ensure that preferences are saved after we have completed resizing, we pass the save function as a callback to the queueUpdate that can then be called in the …
> Resize preference save sequence

- docs-app/app/templates/application.hbs
> fix: link from docs to API documentation (#242)
